apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: db-service
spec:
  type: NodePort
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
  selector:
    app: db-service