version: '3'
services:
    configserver:
      image: configserver
      ports:
       - "8888:8888"
      networks:
       - discovery-config
      links:
       - discovery-server
    discovery-server:
      image: discovery-server
      ports:
       - "8761:8761"
      networks:
       - discovery-config
networks:
  discovery-config: