apiVersion: v1
kind: Service
metadata:
  name: bookservice
  namespace: kube-system
  labels:
    app: bookservice
spec:
  type: NodePort
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
  selector:
    app: bookservice