apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-static-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default-http-backend
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: default-http-backend
    spec:
      containers:
      - name: default-http-backend
        image: nginx-static-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
