apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: kube-system
  labels:
    app: api
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: api