apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-api
  namespace: kube-system
  annotations:
    configmap.reloader.stakater.com/reload: "deploy-api-configmap"
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: api:v1.1
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        volumeMounts:
          - name: api-service-config
            mountPath: "/config"
      volumes:
      - name: api-service-config
        configMap:
          name: deploy-api-configmap
          items:
            - key: application.properties
              path: application.properties